apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment.app }}
  name: {{ .Values.deployment.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
      - image: {{.Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        name: {{ .Values.deployment.app }}