apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: khatanve/hellotanveer:v1
        name: hellotanveer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipeline
  name: pipeline
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: pipeline
  type: NodePort
